apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: <your-vm-name>
  namespace: <your-namespace>
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
            - name: cusa
              bridge: {}
      networks:
        - name: cusa
          multus:
            networkName: cusa-canon
      dnsConfig:
        nameservers:
          - 10.222.159.77
        searches:
          - cusa.canon.com
